// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Study.VS2022.Model.Oracle.CaseDemo
{
    public partial class TOrder
    {
        public string TO_Guid { get; set; }
        public decimal? TO_Price { get; set; }
    }
}