// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Study.VS2022.Model.Oracle.CaseDemo
{
    public partial class TUser
    {
        public string TU_Guid { get; set; }
        public string TU_Account { get; set; }
        public string TU_Password { get; set; }
        public string TU_RealName { get; set; }
    }
}