// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Study.VS2022.Model.MSSQLServer.EFCorePowerTools
{
    public partial class StudyVS2022Context : DbContext
    {
        public StudyVS2022Context()
        {
        }

        public StudyVS2022Context(DbContextOptions<StudyVS2022Context> options)
            : base(options)
        {
        }

        public virtual DbSet<TOrder> TOrder { get; set; }
        public virtual DbSet<TUser> TUser { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TOrder>(entity =>
            {
                entity.HasKey(e => e.TO_GUID)
                    .HasName("PK__TOrder__01D160457F60ED59");

                entity.Property(e => e.TO_GUID).ValueGeneratedNever();
            });

            modelBuilder.Entity<TUser>(entity =>
            {
                entity.HasKey(e => e.TO_GUID)
                    .HasName("PK__TUser__01D1604503317E3D");

                entity.Property(e => e.TO_GUID).ValueGeneratedNever();

                entity.Property(e => e.TU_Account).HasMaxLength(50);

                entity.Property(e => e.TU_Password).HasMaxLength(50);

                entity.Property(e => e.TU_RealName).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}