// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Study.VS2022.Model.MSSQLServer.EFCorePowerTools
{
    public partial class TOrder
    {
        public Guid TO_GUID { get; set; }
        public int? TO_Price { get; set; }
    }
}