// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Study.VS2022.Model.Oracle.OraModels
{
    public partial class TORDER
    {
        public string TO_GUID { get; set; }
        public decimal? TO_PRICE { get; set; }
    }
}