// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Study.VS2022.Model.Oracle.OraModels
{
    public partial class TUSER
    {
        public string TU_GUID { get; set; }
        public string TU_ACCOUNT { get; set; }
        public string TU_PASSWORD { get; set; }
        public string TU_REALNAME { get; set; }
    }
}